### ISSUE TITLE
Make XML EPG is empty

### ISSUE THREAD

**Issue by plimut** [vstavrinov/acestream-service#3]
http://127.0.0.1:8000/search.m3u?xml_epg=true 
`<?xml version="1.0" encoding="utf-8" ?>
<tv>`
Returns empty xml with header.

http://127.0.0.1:8000/search.m3u?json=true
works fine.

Is this a bug or am I setting the request parameter incorrectly?

**Comment by vstavrinov** [comment]
This caused by acestream  update with changed data structure. Fixed:

https://github.com/vstavrinov/acestream_search/commit/7635bd2d6b4f12db61c26a221d2223f82a6fff43

get fresh image to bring it into effect

**Comment by plimut** [comment]
Thanks, the EPG is working fine now.
